Added TSV file update scripts and CI entry.

diff --git a/.gitlab-scripts/deploy-firmware b/.gitlab-scripts/deploy-firmware
--- a/.gitlab-scripts/deploy-firmware
+++ b/.gitlab-scripts/deploy-firmware
@@ -1,10 +1,27 @@
 #!/bin/bash
 current_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null && pwd )"
 
-# Generate the px4 binary
-make px4fmu-v4_default
+# Get version from version file.
+version_file_path="$current_dir/version"
+if [ -f "$version_file_path" ]; then
+    version=$(cat $version_file_path)
+else
+    echo "Could not read version file at $current_dir/version."
+    exit 1
+fi
 
-# Add the px4 binary to the payload directory
+# Generate the px4 binary.
+# make px4fmu-v4_default || exit 1
+
+# Add (and rename) the px4 binary to the payload directory.
 px4_bin_path="/builds/Teal/Flight-Stack/build/nuttx_px4fmu-v4_default/px4fmu-v4_default.px4"
-rsync -aPvz $px4_bin_path $current_dir/payload/
+rsync -aPvz $px4_bin_path $current_dir/payload/v${version}.px4 || exit 1
 
+# Generate TSE file.
+TealSEI/.gitlab-scripts/generate-tse-file payload Teal-PX4-"${version}".tse.jsq || exit 1
+
+# Deploy the TSE file.
+TealSEI/.gitlab-scripts/deploy-artifact-to-s3 TealPX4 *.tse.jsq || exit 1
+
+# Deploy the .px4 file.
+TealSEI/.gitlab-scripts/deploy-artifact-to-s3 TealPX4 *.px4 || exit 1
